// This file is automatically generated. Do not modify.
const firebaseConfig = {
  "projectId": "pdf-annotator-pro-96wd4",
  "appId": "1:515387203541:web:6e928e2fc9c143692c275c",
  "storageBucket": "pdf-annotator-pro-96wd4.firebasestorage.app",
  "apiKey": "AIzaSyC1S0AJ_4ZjFviRVjMdWU8XCCiGQqYNR9I",
  "authDomain": "pdf-annotator-pro-96wd4.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "515387203541"
};
export default firebaseConfig;
